# https://taskfile.dev

version: '3.38'

interval: '100ms'

vars:
  GITHUB_ACTIONS: .github/workflows/github-actions.yml
  DEVCONTAINER_PREFIX: 'mcr.microsoft.com/devcontainers/python:1-'
  MY_PYTHON_VERSION: 3.12


tasks:
  default:
    desc: "Syntax check and unit test"
    deps: [setup, flake8, test]

  watch:
    desc: "Watch flake8 and unit tests"
    deps: [flake8, test]
    watch: true
    sources:
      - '**/*.py'
      - '*.yml'

  flake8:
    aliases: [static]
    desc: "Static analysis"
    watch: true
    cmds:
      - flake8

  test:
    desc: "Unit tests"
    watch: true
    cmds:
      - pytest


  requirements:
    desc: Generate a requirements.txt file
    cmds:
      - |
        pipenv lock
        pipenv requirements > requirements.txt

  setup:
    desc: Write some files
    cmds:
      - echo "FROM {{.DEVCONTAINER_PREFIX}}{{.MY_PYTHON_VERSION}}-bookworm" > Dockerfile
      - sed -i -r -e "s,([ ]+container.[ ]+).*,\1{{.DEVCONTAINER_PREFIX}}{{.MY_PYTHON_VERSION}}-bookworm," {{.GITHUB_ACTIONS}}
      - sed -i -r -e "s,^python_version = \".*\",python_version = \"{{.MY_PYTHON_VERSION}}\"," Pipfile
    requires:
      vars: [MY_PYTHON_VERSION]


  shiv:
    desc: Generate an executable python zip file
    deps: [setup, flake8, test, requirements]
    cmds:
      - |
        shiv -o shiv_cli.pyz -p '/usr/bin/env python3' \
          --site-packages \
          $(pipenv --venv)/lib/python{{.MY_PYTHON_VERSION}}/site-packages \
          -e shiv_cli.cli:main
      - ./shiv_cli.pyz --help
      - ./shiv_cli.pyz -h
    requires:
      vars: [MY_PYTHON_VERSION]
